# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1


# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  build:
    docker:
      - image: circleci/python:3.10

    working_directory: ~/devops_local

    steps:
      #1 Obtain repo from Github
      - checkout
      #2 Create a virtual environment and install dependencies
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            sudo apt-get update
            sudo apt-get install libcups2-dev
            sudo apt-get install libcairo2-dev pkg-config python3-dev
            pip install -r requirements.txt
      #3 Run coding convention software plus tester.
      - run:
          name:  run tests
          command: |
            . venv/bin/activate
            flake8 –-exclude=venv* --statistics
            # pytest -v --cov=calculator
            pytest –-junitxml=test-results/junit.xml
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results